### ISSUE TITLE
What is usecPerSec?

### ISSUE THREAD

**Issue by AlexanderFabisch** [ESROCOS/types-base#6]
The type "Time" contains a field "usecPerSec". In the rock base-types, there is a constant with a similar name in Time: https://github.com/rock-core/base-types/blob/master/src/Time.hpp#L18
I guess this is just a transcription error and you can remove the field from Time.

**Comment by maltewi** [comment]
You're right. As a variable that makes no sense. It should be:
1)  either a constant or 
2) deleted and instead go to a helper library

@mmunoz-gmv, @Kynneb any preference?

**Comment by Kynneb** [comment]
In Rock, this field is only ever used to have a hard coded conversion factor without having an integer literal in the cpp, right? 

As the number should not change much per definition it probably makes sense to have it constant :-D I don't know if a helper library isn't a bit overkill if we don't have a lot of other constants which are actually a bit more sophisticated.

**Comment by mmunoz-gmv** [comment]
This element is an artifact from the automatic conversion from C++ to ASN.1. It can be removed.

**Comment by mmunoz-gmv** [comment]
Deleted in the new data type generated from the tlb file.
