### ISSUE TITLE
Should type names be prefixed by 'T-' ?

### ISSUE THREAD

**Issue by Acwok** [ESROCOS/types-base#8]
We in OG3 INFUSE are using the [Data Modelling Tools](https://github.com/ttsiodras/DataModellingTools#taste-data-modelling-tools) **(DMTs)** of the European Space Agency's TASTE toolchain to generate python code from ESROCOS/types-base asn files.

DMT parses each input .asn files to ensure that TASTE rules are respected and therefore that it will be able to generate code in any language. Generating code from ESROCOS types works fine, however **using ESROCOS types in composed types can cause the following error:**  
```Ada mappers won't allow SEQUENCE/CHOICE fields with same names as their types```

For instance, this error occurs when I try to create a PoseStamped type composed of a Pose and a Time:
```
PoseStamped ::= SEQUENCE
{  
    pose            Pose, 
    header          Header   
}
```
As **'pose'** keyword is already used to represent the **Pose** type, it cannot be used as field name (same thing for 'header').
I think **each type name should be prefixed by 'T-'** as it it already done in taste-types.asn for three main reasons:  
- to avoid the DMT error
- to allow people choosing the name of their fields
- to prevent issues when trying to include time.h which is already a C library

**Comment by AlexanderFabisch** [comment]
@Kynneb @maltewi

**Comment by mmunoz-gmv** [comment]
The new data types generated from the tlb files are prefixed with the c++ namespaces, which should eliminate this problem.
